version: '3.9'

services:
  go.shopdev:
    container_name: go_shopdev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8002
    depends_on:
      - mysql
      - redis
    restart: always
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=goShop
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.0
    container_name: reids_container
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: