server:
  host: "0.0.0.0"
  port: 8002
  mode: "dev"
mysql:
  host: mysql_container
  port: 3306
  username: root
  password: 123456
  dbname: goShop
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600 

log:
  logLevel: debug
  logFileName: "./storages/logs/dev.8386.log"
  maxSize:  10
  maxBackup: 2
  maxAge: 30
  compress: true

redis:
  host: reids_container
  port: 6379
  database: 0
  password: ""
  poolSize: 10