server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: goShop
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600 

log:
  logLevel: debug
  logFileName: "./storages/logs/dev.8386.log"
  maxSize:  10
  maxBackup: 2
  maxAge: 30
  compress: true